- name: Master node cluster init
  hosts: master
  tasks:
    - name: Initialize K8S cluster
      changed_when: false
      ansible.builtin.shell: kubeadm init --pod-network-cidr=172.16.0.0/16 --apiserver-advertise-address=192.168.200.210 --ignore-preflight-errors=all
    - name: Create .kube directory and copy kube config file
      changed_when: false
      ansible.builtin.shell: "{{ item }}"
      loop:
        - mkdir -p $HOME/.kube
        - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        - chown $(id -u):$(id -g) $HOME/.kube/config
    - name: Install Pod network
      become: true
      ansible.builtin.shell: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt
- name: Worker cluster init
  hosts: workers
  tasks:
    - name: Get join command
      changed_when: false
      ansible.builtin.shell: kubeadm token create --print-join-command
      register: join_command_raw
      when: "'master' in group_names"
    - name: Set join command
      ansible.builtin.set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"
      when: "'masters' in group_names"
    - name: Join cluster
      ansible.builtin.shell: "{{ hostvars['master'].join_command }} --ignore-preflight-errors all  >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
      when: "'workers' in group_names"
