- name: Init Docker and Kubernetes
  hosts: master workers
  tasks:
    - name: Add Docker Repository
      changed_when: false
      ansible.builtin.shell: |
        echo deb [trusted=yes] https://download.docker.com/linux/ubuntu noble stable > /tmp/line
        cat /tmp/line > /etc/apt/sources.list.d/docker.list
    - name: Installation of Docker
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose
    - name: Setting value of SystemdCgroup
      changed_when: false
      ansible.builtin.shell: |
        set -o pipefail | containerd config default | sudo tee /etc/containerd/config.toml | grep SystemdCgroup
        sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml
    - name: Starting Service of Docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
    - name: Add k8s gpg key
      changed_when: false
      ansible.builtin.shell: |
        set -o pipefail | curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --batch --yes --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    - name: Add Kubernetesapt repository
      changed_when: false
      ansible.builtin.shell: |
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' > /tmp/line
        cat /tmp/line > /etc/apt/sources.list.d/kubernetes.list
    - name: Install kubelet
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - kubelet
    - name: Start kubelet
      ansible.builtin.service:
        name: kubelet
        enabled: true
        state: started
    - name: Install kubectl
      ansible.builtin.apt:
        name: kubectl
        state: present
    - name: Install kubeadm
      ansible.builtin.apt:
        name: "kubeadm"
        state: present
