- name: Common master and worker initialization
  hosts: master workers
  tasks:
    - name: Disable SWAP
      changed_when: false
      ansible.builtin.shell: |
        swapoff -a
    - name: Disable SWAP in fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^.*swap.*$'
        line: '#\0'
        backrefs: true
    - name: System upgrade
      ansible.builtin.apt:
        upgrade: dist
    - name: Installation of apt-utils
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
    - name: Add k8s gpg key
      ansible.builtin.apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
        state: present
    - name: Add Kubernetesapt repository
      changed_when: false
      ansible.builtin.shell: |
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' > /tmp/line
        cat /tmp/line > /etc/apt/sources.list.d/kubernetes.list
    - name: Install kubelet
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - kubelet
- name: Initialize master node
  hosts: master
  tasks:
    - name: Install kubeadm
      ansible.builtin.apt:
        name: "kubeadm"
        state: present
    - name: Start kubelet
      ansible.builtin.service:
        name: kubelet
        enabled: true
        state: started
    - name: Install kubectl
      ansible.builtin.apt:
        name: kubectl
        state: present
- name: Initialize worker nodes
  hosts: workers
  tasks:
    - name: Add Docker Repository
      changed_when: false
      ansible.builtin.shell: |
        echo 'deb [trusted=yes] https://download.docker.com/linux/ubuntu ${. /etc/os-release && echo $VERSION_CODENAME} stable' > /tmp/line
        cat /tmp/line > /etc/apt/sources.list.d/docker.list
    - name: Installation of Docker
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose
    - name: Setting value of SystemdCgroup
      changed_when: false
      ansible.builtin.shell: |
        set -o pipefail && containerd config default | sudo tee /etc/containerd/config.toml | grep SystemdCgroup
        sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml
    - name: Starting Service of Docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
    - name: Start kubelet
      ansible.builtin.service:
        name: kubelet
        enabled: true
        state: started
